version: '3'

services:
  eamashop.identity.api:
    image: eamashop.identity.api
    build:
      context: ./src/EamaShop.Identity.API
      dockerfile: Dockerfile
    depends_on:
      - postgres.db
  postgres.db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=123456
    ports:
      - "5432:5432"
