version: '3'

services:
  eamashop_identity_api:
    image: registry.cn-hangzhou.aliyuncs.com/wuyafeng/eamashop.identity.api
    depends_on:
      - postgres_db
    ports:
      - "8989:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - webnet
  postgres_db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=123456
    ports:
      - "5432:5432"
networks:
  webnet: