// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace EamaShop.Identity.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class UserPasswordPutDTO
    {
        /// <summary>
        /// Initializes a new instance of the UserPasswordPutDTO class.
        /// </summary>
        public UserPasswordPutDTO() { }

        /// <summary>
        /// Initializes a new instance of the UserPasswordPutDTO class.
        /// </summary>
        public UserPasswordPutDTO(string newPassword, string token)
        {
            NewPassword = newPassword;
            Token = token;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "NewPassword")]
        public string NewPassword { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Token")]
        public string Token { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (NewPassword == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "NewPassword");
            }
            if (Token == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Token");
            }
            if (this.NewPassword != null)
            {
                if (this.NewPassword.Length > 18)
                {
                    throw new ValidationException(ValidationRules.MaxLength, "NewPassword", 18);
                }
                if (this.NewPassword.Length < 6)
                {
                    throw new ValidationException(ValidationRules.MinLength, "NewPassword", 6);
                }
            }
        }
    }
}
