// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace EamaShop.Identity.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class UserPhonePutDTO
    {
        /// <summary>
        /// Initializes a new instance of the UserPhonePutDTO class.
        /// </summary>
        public UserPhonePutDTO() { }

        /// <summary>
        /// Initializes a new instance of the UserPhonePutDTO class.
        /// </summary>
        public UserPhonePutDTO(string phone, string verifyCode)
        {
            Phone = phone;
            VerifyCode = verifyCode;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Phone")]
        public string Phone { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "VerifyCode")]
        public string VerifyCode { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (Phone == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Phone");
            }
            if (VerifyCode == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "VerifyCode");
            }
        }
    }
}
